---
- name: Install jenkins
  hosts: localhost
  become: yes
  become_user: root 

  tasks:
    - name: Update all package to latest version.
      apt:
        name: "*"
        state: latest
  
    - name: Download jenkins key 
       ansible.buildin.get_url
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /etc/apt/keyrings/jenkins-keyring.asc
    
    - name: Add jenkins 
      apt_repo:
      repo: deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins.list
    
    - name: Update all package to their latest version.
      apt:
        name: "*"
        state: latest

    - name: Install fontconfig
      shell: apt install fontconfig -y 

    - name: install java 
      shell: apt install fontconfig openjdk-21-jre -y 

    - name: Install jenkins
      ansible.buildin.apt:
        name: jenkins
        state: present

    - name: make sure service is running.
      ansible.buildin.systemd:
        name: jenkins
        enabled: yes
